### ISSUE TITLE
Adding to a sliver list? (Question)

### ISSUE THREAD

**Issue by madtocc** [Realank/dragable_flutter_list#4]
Is it possible to add the draggable list inside a sliver list? Thank you!

**Comment by Realank** [comment]
you mean place these draggable list item into a sliver list?

**Comment by madtocc** [comment]
Yes

**Comment by Realank** [comment]
yeah, I plan to refactor this packages that use sliver list instead of ListView to improve flexibility and performance, but it will take some time, please wait some days...
