### ISSUE TITLE
Drag and drop by dragging an icon, not the row itself?

### ISSUE THREAD

**Issue by kevincherryholme** [Realank/dragable_flutter_list#5]
Hi!

So to start dragging a list item you have to long press an item, and then drag to the desired position.

Is it possible that we can isolate the draggable area to an icon? AND instead of needing to long press, can we just tap your finger and it immediately allows you to drag?

For example: (sorry for the horrible quality)
![image](https://user-images.githubusercontent.com/17769477/49469210-ef04d980-f7d4-11e8-9527-072966668e86.png)

Thanks!!

**Comment by Realank** [comment]
Sure, you can change the codes to achieve this behavior, but I don't want to add the feature in this package currently sorry for that
