### ISSUE TITLE
Drag&Drop reorder between two lists

### ISSUE THREAD

**Issue by godzeit** [Realank/dragable_flutter_list#6]
Hello!

I am trying to create some sort of task manager exactly like in trello and your library solving my problem of drag&droping perfectly, but now fully. Can you please make possivle to drag&drop item of list between two and more lists.

![trello](https://user-images.githubusercontent.com/48680083/54532217-0d1fcf80-49a9-11e9-9c5e-413d50bc7b70.gif)

**Comment by Realank** [comment]
it looks so complicated , and I think I can't implemented in this packages, but I think you can optimize this package to achieve that
