### ISSUE TITLE
Indexing Issue

### ISSUE THREAD

**Issue by ThomasValois** [Realank/dragable_flutter_list#9]
### Issue

Hi there, I've started using your package because it's one of the simplest on pub.dev but I'm having some issues integrating this with Firestore. When trying to "pick up" the object, it's not setting the correct item. I was wondering if this is related to your package? I've tried wrapping this in a Listener widget but this causes the package to not work.

### Relevant Code

```
DragAndDropList(
                      snapshot.data.documents.length,
                      itemBuilder: (BuildContext context, index) {
                        DocumentSnapshot documentSnapshot =
                            snapshot.data.documents[index];
                        _index = snapshot.data.documents[index];
```

```
onDragFinish: (before, after) {
                        print('${_index.documentID} $after');
                        Firestore.instance
                            .collection('users')
                            .document(userDocPATH)
                            .collection(userDashboardPATH)
                            .document(_index.documentID)
                            .updateData({'Position': after.toString()});
                      },
```

**Comment by Realank** [comment]
I think the variant _index is used in wrong way, it is updated in itemBuilder, but in onDragFinish, you should update it with _index = snapshot.data.documents[before];
